steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/catalogue:$COMMIT_SHA'
      - -t
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/catalogue:latest'
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - --all-tags
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/catalogue'

substitutions:
  _REGION: europe-west1
  _REPOSITORY: prt-prod-docker 

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/catalogue:$COMMIT_SHA'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/catalogue:latest'
